### ISSUE TITLE
🎈 Roadmap for Ideas and Suggestions

### ISSUE THREAD

**Issue by kangarko** [kangarko/ChatControl#1]
<h1><p align="center">A List of Ideas and Suggested Features</p></h1>

_Due to a tiny team we are at present not open for features. There is no ETA. All features are consideration only._

**High priority**
- [X] Velocity support
- [X] HikariCP https://github.com/brettwooldridge/HikariCP
- [X] Support "require sender/receiver server" placeholders, https://github.com/kangarko/ChatControl-Red/issues/1492
- [ ] Spying only for certain players https://github.com/kangarko/ChatControl-Red/issues/2248
- [ ] BungeeCord motd and broadcast system, https://github.com/kangarko/ChatControl-Red/issues/384
- [ ] For staff, GUI for canned replies https://github.com/kangarko/ChatControl-Red/issues/1476
- [ ] Support gradients in chat, https://github.com/kangarko/ChatControl-Red/issues/1777
- [ ] Format messages with paginator https://github.com/kangarko/ChatControl-Red/issues/1910
- [ ] Ability to send some of our messages as boss bar, title, actionbar https://github.com/kangarko/ChatControl-Red/issues/1998
- [ ] Fix long standing issue of "unknown packed identifier" https://github.com/kangarko/ChatControl-Red/issues/1951

**Normal priority**
- [ ] Linking with Discord https://github.com/DiscordSRV/DiscordSRV/wiki/linking
- [ ] Bungee sync for settings.yml or parts of it  (see how PLAN does their config management)
- [ ] Allow players to change their colors like OmegaNames, https://github.com/kangarko/ChatControl-Red/issues/282
- [ ] Have the {recipient_X} variables be compatible with private messages
- [x] Spying on local chat channels

**Low priority**
- [ ] Captcha for anti-bot
- [ ] Motd in the real sense, /motd folder with messages for every day
- [ ] /menu -> for major options & creating fancy rules
- [ ] Create channels in-game and use passwords to join them https://github.com/kangarko/ChatControl-Red/issues/913
